parameters:
#    bbit_async_dispatcher.example.class: BBIT\AsyncDispatcherBundle\Example

#services:
#    bbit_async_dispatcher.example:
#        class: %bbit_async_dispatcher.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
services:
    bbit_async_dispatcher.dispatcher:
        class: BBIT\AsyncDispatcherBundle\Component\EventDispatcher\AsynchronousEventDispatcher
        arguments:
            - @event_dispatcher
    bbit_async_dispatcher.listener.terminate:
        class: BBIT\AsyncDispatcherBundle\Component\EventDispatcher\AsynchronousEventListener
        arguments:
            - @bbit_async_dispatcher.dispatcher
        tags:
            - { name: 'kernel.event_listener', event: 'kernel.terminate' }